<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="1" failed="1" skipped="3">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-03-21T09:06:43 CET" name="Default suite" finished-at="2024-03-21T09:07:14 CET" duration-ms="30892">
    <groups>
      <group name="recomendaciones">
        <method signature="Prueba1test.testRecomendaciones()[pri:0, instance:efemispruebas.Prueba1test@3e27aa33]" name="testRecomendaciones" class="efemispruebas.Prueba1test"/>
      </group> <!-- recomendaciones -->
      <group name="planificacion">
        <method signature="Prueba1test.testPlanificarRecomendacion()[pri:0, instance:efemispruebas.Prueba1test@3e27aa33]" name="testPlanificarRecomendacion" class="efemispruebas.Prueba1test"/>
      </group> <!-- planificacion -->
      <group name="ejecucion">
        <method signature="Prueba1test.testEjecutarPlanificacion()[pri:0, instance:efemispruebas.Prueba1test@3e27aa33]" name="testEjecutarPlanificacion" class="efemispruebas.Prueba1test"/>
      </group> <!-- ejecucion -->
      <group name="menu">
        <method signature="Prueba1test.testMenu()[pri:0, instance:efemispruebas.Prueba1test@3e27aa33]" name="testMenu" class="efemispruebas.Prueba1test"/>
      </group> <!-- menu -->
      <group name="login">
        <method signature="Prueba1test.testLogin()[pri:0, instance:efemispruebas.Prueba1test@3e27aa33]" name="testLogin" class="efemispruebas.Prueba1test"/>
      </group> <!-- login -->
    </groups>
    <test started-at="2024-03-21T09:06:43 CET" name="Default test" finished-at="2024-03-21T09:07:14 CET" duration-ms="30892">
      <class name="efemispruebas.Prueba1test">
        <test-method is-config="true" signature="setUp()[pri:0, instance:efemispruebas.Prueba1test@3e27aa33]" started-at="2024-03-21T09:06:43 CET" name="setUp" finished-at="2024-03-21T09:06:45 CET" duration-ms="1742" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testLogin()[pri:0, instance:efemispruebas.Prueba1test@3e27aa33]" started-at="2024-03-21T09:06:45 CET" name="testLogin" finished-at="2024-03-21T09:06:49 CET" duration-ms="4258" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:efemispruebas.Prueba1test@3e27aa33]" started-at="2024-03-21T09:06:49 CET" name="setUp" finished-at="2024-03-21T09:06:50 CET" duration-ms="733" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testMenu()[pri:0, instance:efemispruebas.Prueba1test@3e27aa33]" started-at="2024-03-21T09:06:50 CET" name="testMenu" depends-on-groups="login" finished-at="2024-03-21T09:07:14 CET" duration-ms="24036" status="FAIL">
          <exception class="org.openqa.selenium.TimeoutException">
            <message>
              <![CDATA[Expected condition failed: waiting for element to be clickable: By.xpath: //div[@id='main-view']/div[2]/div/div[2]/div/div[3]/a/span[2] (tried for 20 second(s) with 500 milliseconds interval)]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.TimeoutException: Expected condition failed: waiting for element to be clickable: By.xpath: //div[@id='main-view']/div[2]/div/div[2]/div/div[3]/a/span[2] (tried for 20 second(s) with 500 milliseconds interval)
at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:95)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:272)
at efemispruebas.Menu.MenuDesplegable(Menu.java:23)
at efemispruebas.Prueba1test.menu(Prueba1test.java:87)
at efemispruebas.Prueba1test.testMenu(Prueba1test.java:43)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@id='main-view']/div[2]/div/div[2]/div/div[3]/a/span[2]"}
  (Session info: chrome=122.0.6261.129)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'PRESTAMOS-PC101', ip: '192.168.1.135', os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.21'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 122.0.6261.129, chrome: {chromedriverVersion: 122.0.6261.94 (880dbf29479c..., userDataDir: C:\Users\usuario\AppData\Lo...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:55903}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 9606b0e7915ddba1abf2305a726b1d7f
*** Element info: {Using=xpath, value=//div[@id='main-view']/div[2]/div/div[2]/div/div[3]/a/span[2]}
at jdk.internal.reflect.GeneratedConstructorAccessor10.newInstance(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:428)
at org.openqa.selenium.By$ByXPath.findElement(By.java:353)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:315)
at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:205)
at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:201)
at org.openqa.selenium.support.ui.ExpectedConditions$22.apply(ExpectedConditions.java:641)
at org.openqa.selenium.support.ui.ExpectedConditions$22.apply(ExpectedConditions.java:638)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:249)
... 31 more
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.TimeoutException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMenu -->
        <test-method signature="testRecomendaciones()[pri:0, instance:efemispruebas.Prueba1test@3e27aa33]" started-at="2024-03-21T09:07:14 CET" name="testRecomendaciones" depends-on-groups="menu" finished-at="2024-03-21T09:07:14 CET" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Prueba1test.testRecomendaciones()[pri:0, instance:efemispruebas.Prueba1test@3e27aa33] depends on not successfully finished methods in group "menu"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Prueba1test.testRecomendaciones()[pri:0, instance:efemispruebas.Prueba1test@3e27aa33] depends on not successfully finished methods in group "menu"
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:157)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testRecomendaciones -->
        <test-method signature="testPlanificarRecomendacion()[pri:0, instance:efemispruebas.Prueba1test@3e27aa33]" started-at="2024-03-21T09:07:14 CET" name="testPlanificarRecomendacion" depends-on-groups="recomendaciones" finished-at="2024-03-21T09:07:14 CET" duration-ms="1" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Prueba1test.testPlanificarRecomendacion()[pri:0, instance:efemispruebas.Prueba1test@3e27aa33] depends on not successfully finished methods in group "recomendaciones"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Prueba1test.testPlanificarRecomendacion()[pri:0, instance:efemispruebas.Prueba1test@3e27aa33] depends on not successfully finished methods in group "recomendaciones"
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:157)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPlanificarRecomendacion -->
        <test-method signature="testEjecutarPlanificacion()[pri:0, instance:efemispruebas.Prueba1test@3e27aa33]" started-at="2024-03-21T09:07:14 CET" name="testEjecutarPlanificacion" depends-on-groups="planificacion" finished-at="2024-03-21T09:07:14 CET" duration-ms="1" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Prueba1test.testEjecutarPlanificacion()[pri:0, instance:efemispruebas.Prueba1test@3e27aa33] depends on not successfully finished methods in group "planificacion"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Prueba1test.testEjecutarPlanificacion()[pri:0, instance:efemispruebas.Prueba1test@3e27aa33] depends on not successfully finished methods in group "planificacion"
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:157)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testEjecutarPlanificacion -->
      </class> <!-- efemispruebas.Prueba1test -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
